version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: shoppingao-postgres
    restart: always
    environment:
      POSTGRES_USER: Shoppingao
      POSTGRES_PASSWORD: touro1234
      POSTGRES_DB: shoppingao-user
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: shoppingao-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shoppingao.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
