services:
  postgres:
    image: postgres:latest
    container_name: shoppingao-postgres
    restart: always
    environment:
      POSTGRES_USER: Shoppingao
      POSTGRES_PASSWORD: touro1234
      POSTGRES_DB: shoppingao_user   
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
